import hashlib
from datetime import datetime, timezone
import io
import uuid

import fitz  # PyMuPDF
from sqlalchemy.orm import Session

from app.models.file import File
from app.models.user import User
from app.services.storage.factory import get_storage_provider


class AuditService:
    def __init__(self, db: Session):
        self.db = db

    def generate_certificate(
        self,
        file: File,
        signer_user: User,
        client_ip: str = "127.0.0.1",
        user_agent: str = "Web Browser",
    ) -> bytes:
        storage = get_storage_provider()
        content = storage.read(file.storage_key)
        sha256_hash = hashlib.sha256(content).hexdigest()
        now = datetime.now(timezone.utc)
        timestamp_str = now.strftime("%Y-%m-%d %H:%M:%S UTC")

        # Create a new 1-page PDF document
        doc = fitz.open()
        page = doc.new_page(width=595, height=842)  # A4 size in points

        # Draw background and header styling
        # Top banner background: Dark slate
        page.draw_rect(fitz.Rect(0, 0, 595, 110), color=None, fill=(0.04, 0.08, 0.15))
        # Accent gold bar
        page.draw_rect(fitz.Rect(0, 106, 595, 110), color=None, fill=(0.95, 0.65, 0.14))

        # Title
        page.insert_text(
            fitz.Point(40, 52),
            "PDF360 CERTIFICATE OF COMPLETION",
            fontsize=20,
            fontname="helv",
            color=(1, 1, 1),
        )
        page.insert_text(
            fitz.Point(40, 78),
            "Tamper-Evident Audit Trail & Digital Signature Record",
            fontsize=11,
            fontname="helv",
            color=(0.8, 0.8, 0.8),
        )

        # Document Details Box
        page.draw_rect(fitz.Rect(40, 135, 555, 275), color=(0.85, 0.88, 0.92), fill=(0.97, 0.98, 0.99))
        page.insert_text(fitz.Point(55, 160), "DOCUMENT INFORMATION", fontsize=11, fontname="helv", color=(0.1, 0.15, 0.25))

        page.insert_text(fitz.Point(55, 185), f"Document Title: {file.original_filename}", fontsize=10, fontname="helv", color=(0.2, 0.2, 0.2))
        page.insert_text(fitz.Point(55, 205), f"Document ID: {str(file.id)}", fontsize=9, fontname="helv", color=(0.3, 0.3, 0.3))
        page.insert_text(fitz.Point(55, 225), f"File Size: {file.size_bytes:,} bytes", fontsize=9, fontname="helv", color=(0.3, 0.3, 0.3))
        page.insert_text(fitz.Point(55, 245), f"SHA-256 Digest: {sha256_hash}", fontsize=8.5, fontname="courier", color=(0.15, 0.2, 0.3))
        page.insert_text(fitz.Point(55, 265), f"Certification Timestamp: {timestamp_str}", fontsize=9, fontname="helv", color=(0.3, 0.3, 0.3))

        # Signer & Participant Information Box
        page.draw_rect(fitz.Rect(40, 295, 555, 455), color=(0.85, 0.88, 0.92), fill=(0.97, 0.98, 0.99))
        page.insert_text(fitz.Point(55, 320), "SIGNER & IDENTITY VERIFICATION", fontsize=11, fontname="helv", color=(0.1, 0.15, 0.25))

        page.insert_text(fitz.Point(55, 345), f"Signer Name: {signer_user.full_name or signer_user.email}", fontsize=10, fontname="helv", color=(0.2, 0.2, 0.2))
        page.insert_text(fitz.Point(55, 365), f"Signer Email: {signer_user.email}", fontsize=10, fontname="helv", color=(0.2, 0.2, 0.2))
        page.insert_text(fitz.Point(55, 385), f"Account ID: {str(signer_user.id)}", fontsize=9, fontname="helv", color=(0.3, 0.3, 0.3))
        page.insert_text(fitz.Point(55, 405), f"Signing IP Address: {client_ip}", fontsize=9, fontname="helv", color=(0.3, 0.3, 0.3))
        page.insert_text(fitz.Point(55, 425), f"Client Environment: {user_agent[:60]}", fontsize=8.5, fontname="helv", color=(0.4, 0.4, 0.4))
        page.insert_text(fitz.Point(55, 445), "Status: Verified & Digitally Executed", fontsize=9.5, fontname="helv", color=(0.08, 0.55, 0.25))

        # Compliance & Security Seal Box
        page.draw_rect(fitz.Rect(40, 475, 555, 620), color=(0.85, 0.88, 0.92), fill=(0.97, 0.98, 0.99))
        page.insert_text(fitz.Point(55, 500), "LEGAL & REGULATORY COMPLIANCE", fontsize=11, fontname="helv", color=(0.1, 0.15, 0.25))
        
        compliance_text = (
            "This electronic signature certificate was generated by PDF360 Enterprise Document Cloud in compliance with\n"
            "the United States Electronic Signatures in Global and National Commerce Act (E-SIGN, 15 U.S.C. 7001 et seq.)\n"
            "and the Uniform Electronic Transactions Act (UETA). The cryptographic SHA-256 hash above uniquely binds\n"
            "the referenced document content to the recorded audit events and guarantees tamper-evident validation."
        )
        y = 525
        for line in compliance_text.split("\n"):
            page.insert_text(fitz.Point(55, y), line, fontsize=8.5, fontname="helv", color=(0.3, 0.35, 0.4))
            y += 18

        # Signature Seal Stamp
        page.draw_rect(fitz.Rect(55, 660, 250, 740), color=(0.2, 0.6, 0.3), fill=(0.92, 0.98, 0.94), width=1.5)
        page.insert_text(fitz.Point(70, 688), "DIGITALLY VERIFIED", fontsize=11, fontname="helv", color=(0.1, 0.5, 0.2))
        page.insert_text(fitz.Point(70, 706), "PDF360 Audit Engine", fontsize=9, fontname="helv", color=(0.3, 0.4, 0.3))
        page.insert_text(fitz.Point(70, 724), f"Security ID: {str(uuid.uuid4())[:18]}", fontsize=8, fontname="courier", color=(0.3, 0.3, 0.3))

        # Footer
        page.draw_line(fitz.Point(40, 785), fitz.Point(555, 785), color=(0.85, 0.85, 0.85), width=0.5)
        page.insert_text(
            fitz.Point(40, 805),
            f"PDF360 Enterprise Document Cloud · Audit Record generated {timestamp_str} · Page 1 of 1",
            fontsize=8,
            fontname="helv",
            color=(0.5, 0.5, 0.5),
        )

        pdf_bytes = doc.tobytes()
        doc.close()
        return pdf_bytes
